name: docker-deploy
on:
  push:
    branches: [ "dockerimage" ]
jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Generate tag
      id: tag
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: soundnw/fullstack:${{ steps.tag.outputs.TAG }}

    - name: Update Docker Compose file
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_KEY }}
        SERVER_USER: ${{ secrets.USER }}
        SERVER_HOST: ${{ secrets.HOST }}
        DOCKER_COMPOSE_PATH: /root/CICD-react-frontend/docker-compose.yml
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -i ssh_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          sed -i '/services:/,/ports:/ s|image:.*|image: soundnw/fullstack:${{ steps.tag.outputs.TAG }}|' $DOCKER_COMPOSE_PATH
        "

    - name: Restart Docker Compose
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_KEY }}
        SERVER_USER: ${{ secrets.USER }}
        SERVER_HOST: ${{ secrets.HOST }}
        DOCKER_COMPOSE_PATH: ${{ secrets.HOST }}
      run: |
        ssh -i ssh_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          cd $(dirname $DOCKER_COMPOSE_PATH)
          docker-compose down
          docker-compose up -d
        "

          
          
