name: docker-deploy
on:
  push:
    branches: [ "docker" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build tag and push 
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: soundnw/fullstack
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Linode instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /CICD-react-frontend
          sudo git pull origin
          sudo docker-compose pull
          sudo docker-compose up --force-recreate
