name: docker-deploy
on:
  push:
    branches: [ "dockerimage" ]
jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Generate tag
      id: tag
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: soundnw/fullstack:${{ steps.tag.outputs.TAG }}
  Deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-to-dockerhub 
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Update Docker Compose file
          sed -i '/services:/,/ports:/ s|image:.*|image: your-dockerhub-username/react-app:${{ steps.tag.outputs.TAG }}|' /path/to/docker-compose.yml
         
          # Restart Docker Compose
          cd /root/CICD-react-frontend
          sudo git checkout dockerimage
          sudo git pull dockerimage
          docker-compose down
          sudo docker-compose pull
          docker-compose up -d